import re
from bs4 import BeautifulSoup

terminos = [
    ("proveedor posterior", "downstream provider", "un proveedor de un sistema de IA, también de un sistema de IA de uso general, que integra un modelo de IA, con independencia de que el modelo de IA lo proporcione él mismo y esté integrado verticalmente o lo proporcione otra entidad en virtud de relaciones contractuales."),
    ("proveedor","provider", "una persona física o jurídica, autoridad pública, órgano u organismo que desarrolle un sistema de IA o un modelo de IA de uso general o para el que se desarrolle un sistema de IA o un modelo de IA de uso general y lo introduzca en el mercado o ponga en servicio el sistema de IA con su propio nombre o marca, previo pago o gratuitamente;"),
    ("proveedores","provider", "una persona física o jurídica, autoridad pública, órgano u organismo que desarrolle un sistema de IA o un modelo de IA de uso general o para el que se desarrolle un sistema de IA o un modelo de IA de uso general y lo introduzca en el mercado o ponga en servicio el sistema de IA con su propio nombre o marca, previo pago o gratuitamente;"),
    ("responsable del despliegue", "deployer","una persona física o jurídica, o autoridad pública, órgano u organismo que utilice un sistema de IA bajo su propia autoridad, salvo cuando su uso se enmarque en una actividad personal de carácter no profesional;"),
    ("responsables del despliegue", "deployer","una persona física o jurídica, o autoridad pública, órgano u organismo que utilice un sistema de IA bajo su propia autoridad, salvo cuando su uso se enmarque en una actividad personal de carácter no profesional;"),
    ("representante autorizado", "authorised representative", "una persona física o jurídica ubicada o establecida en la Unión que haya recibido y aceptado el mandato por escrito de un proveedor de un sistema de IA o de un modelo de IA de uso general para cumplir las obligaciones y llevar a cabo los procedimientos establecidos en el presente Reglamento en representación de dicho proveedor;"),
    ("representantes autorizado", "authorised representative", "una persona física o jurídica ubicada o establecida en la Unión que haya recibido y aceptado el mandato por escrito de un proveedor de un sistema de IA o de un modelo de IA de uso general para cumplir las obligaciones y llevar a cabo los procedimientos establecidos en el presente Reglamento en representación de dicho proveedor;"),
    ("importador", "importer", "una persona física o jurídica ubicada o establecida en la Unión que introduzca en el mercado un sistema de IA que lleve el nombre o la marca de una persona física o jurídica establecida en un tercer país;"),
    ("distribuidor", "distributor", "una persona física o jurídica que forme parte de la cadena de suministro, distinta del proveedor o el importador, que comercialice un sistema de IA en el mercado de la Unión;"),
    ("operadores", "operator", "un proveedor, fabricante del producto, responsable del despliegue, representante autorizado, importador o distribuidor;"),
    ("operador", "operator", "un proveedor, fabricante del producto, responsable del despliegue, representante autorizado, importador o distribuidor;"),
    ("introducción en el mercado", "placing on the market", "la primera comercialización en el mercado de la Unión de un sistema de IA o de un modelo de IA de uso general;"),
    ("comercialización", "making available on the market", "el suministro de un sistema de IA o de un modelo de IA de uso general para su distribución o utilización en el mercado de la Unión en el transcurso de una actividad comercial, previo pago o gratuitamente;"),
    ("puesta en servicio", "putting into service", "el suministro de un sistema de IA para su primer uso directamente al responsable del despliegue o para uso propio en la Unión para su finalidad prevista;"),
    ("finalidad prevista", "intended purpose", "el uso para el que un proveedor concibe un sistema de IA, incluidos el contexto y las condiciones de uso concretos, según la información facilitada por el proveedor en las instrucciones de uso, los materiales y las declaraciones de promoción y venta, y la documentación técnica;"),
    ("finalidades previstas", "intended purpose", "el uso para el que un proveedor concibe un sistema de IA, incluidos el contexto y las condiciones de uso concretos, según la información facilitada por el proveedor en las instrucciones de uso, los materiales y las declaraciones de promoción y venta, y la documentación técnica;"),
    ("uso indebido razonablemente previsible","reasonably foreseeable misuse","la utilización de un sistema de IA de un modo que no corresponde a su finalidad prevista, pero que puede derivarse de un comportamiento humano o una interacción con otros sistemas, incluidos otros sistemas de IA, razonablemente previsible;"),
    ("componente de seguridad", "safety component", "un componente de un producto o un sistema de IA que cumple una función de seguridad para dicho producto o sistema de IA, o cuyo fallo o defecto de funcionamiento pone en peligro la salud y la seguridad de las personas o los bienes;"),
    ("componentes de seguridad", "safety component", "un componente de un producto o un sistema de IA que cumple una función de seguridad para dicho producto o sistema de IA, o cuyo fallo o defecto de funcionamiento pone en peligro la salud y la seguridad de las personas o los bienes;"),
    ("instrucciones de uso", "instructions for use", "la información facilitada por el proveedor para informar al responsable del despliegue, en particular, de la finalidad prevista y de la correcta utilización de un sistema de IA;"),
    ("recuperación", "recall of an AI system", "(de un sistema de IA) toda medida encaminada a conseguir la devolución al proveedor de un sistema de IA puesto a disposición de los responsables del despliegue, a inutilizarlo o a desactivar su uso;"),
    ("retirada", "withdrawal of an AI system", "(de un sistema de IA) toda medida destinada a impedir la comercialización de un sistema de IA que se encuentra en la cadena de suministro;"),
    ("funcionamiento de un sistema de IA", "performance of an AI system", "la capacidad de un sistema de IA para alcanzar su finalidad prevista;"),
    ("autoridad notificante", "notifying authority", "la autoridad nacional responsable de establecer y llevar a cabo los procedimientos necesarios para la evaluación, designación y notificación de los organismos de evaluación de la conformidad, así como de su supervisión;"),
    ("autoridades notificantes", "notifying authority", "la autoridad nacional responsable de establecer y llevar a cabo los procedimientos necesarios para la evaluación, designación y notificación de los organismos de evaluación de la conformidad, así como de su supervisión;"),
    ("organismo de evaluación de la conformidad", "conformity assessment body", "(evaluación de la conformidad) un organismo que desempeña actividades de evaluación de la conformidad de terceros, como el ensayo, la certificación y la inspección;"),
    ("organismos de evaluación de la conformidad", "conformity assessment body", "(evaluación de la conformidad) un organismo que desempeña actividades de evaluación de la conformidad de terceros, como el ensayo, la certificación y la inspección;"),
    ("evaluación de la conformidad", "conformity assessment", "el proceso por el que se demuestra si se han cumplido los requisitos establecidos en el capítulo III, sección 2, en relación con un sistema de IA de alto riesgo;"),
    ("organismo notificado", "notified body", "un organismo de evaluación de la conformidad notificado con arreglo al presente Reglamento y a otros actos pertinentes de la legislación de armonización de la Unión;"),
    ("organismos notificados", "notified body", "un organismo de evaluación de la conformidad notificado con arreglo al presente Reglamento y a otros actos pertinentes de la legislación de armonización de la Unión;"),
    ("modificación sustancial", "substantial modification", "un cambio en un sistema de IA tras su introducción en el mercado o puesta en servicio que no haya sido previsto o proyectado en la evaluación de la conformidad inicial realizada por el proveedor y a consecuencia del cual se vea afectado el cumplimiento por parte del sistema de IA de los requisitos establecidos en el capítulo III, sección 2, o que dé lugar a una modificación de la finalidad prevista para la que se haya evaluado el sistema de IA de que se trate;"),
    ("modificaciones sustanciales", "substantial modification", "un cambio en un sistema de IA tras su introducción en el mercado o puesta en servicio que no haya sido previsto o proyectado en la evaluación de la conformidad inicial realizada por el proveedor y a consecuencia del cual se vea afectado el cumplimiento por parte del sistema de IA de los requisitos establecidos en el capítulo III, sección 2, o que dé lugar a una modificación de la finalidad prevista para la que se haya evaluado el sistema de IA de que se trate;"),
    ("marcado CE", "CE marking", "un marcado con el que un proveedor indica que un sistema de IA es conforme con los requisitos establecidos en el capítulo III, sección 2, y con otros actos aplicables de la legislación de armonización de la Unión que prevén su colocación;"),
    ("sistema de vigilancia poscomercialización", "post-market monitoring system", "todas las actividades realizadas por los proveedores de sistemas de IA destinadas a recoger y examinar la experiencia obtenida con el uso de sistemas de IA que introducen en el mercado o ponen en servicio, con objeto de detectar la posible necesidad de aplicar inmediatamente cualquier tipo de medida correctora o preventiva que resulte necesaria;"),
    ("autoridad de vigilancia del mercado", "market surveillance authority", "la autoridad nacional que lleva a cabo las actividades y adopta las medidas previstas en el Reglamento (UE) 2019/1020;"),
    ("autoridades de vigilancia del mercado", "market surveillance authority", "la autoridad nacional que lleva a cabo las actividades y adopta las medidas previstas en el Reglamento (UE) 2019/1020;"),
    ("norma armonizada", "harmonised standard", "una norma armonizada tal como se define en el artículo 2, punto 1, letra c), del Reglamento (UE) n.o 1025/2012;"),
    ("especificación común", "common specification", "un conjunto de especificaciones técnicas tal como se definen en el artículo 2, punto 4, del Reglamento (UE) n.o 1025/2012 que proporciona medios para cumplir determinados requisitos establecidos en virtud del presente Reglamento;"),
    ("datos de entrenamiento", "training data", "los datos usados para entrenar un sistema de IA mediante el ajuste de sus parámetros entrenables;"),
    ("datos de validación", "validation data", "los datos usados para proporcionar una evaluación del sistema de IA entrenado y adaptar sus parámetros no entrenables y su proceso de aprendizaje para, entre otras cosas, evitar el subajuste o el sobreajuste;"),
    #("conjunto de datos de validación", "validation data set", "(datos de validación) un conjunto de datos independiente o una parte del conjunto de datos de entrenamiento, obtenida mediante una división fija o variable;"),
    ("datos de prueba", "testing data", "los datos usados para proporcionar una evaluación independiente del sistema de IA, con el fin de confirmar el funcionamiento previsto de dicho sistema antes de su introducción en el mercado o su puesta en servicio;"),
    ("datos de entrada", "input data", "los datos proporcionados a un sistema de IA u obtenidos directamente por él a partir de los cuales produce un resultado de salida;"),
    ("datos biométricos", "biometric data", "los datos personales obtenidos a partir de un tratamiento técnico específico, relativos a las características físicas, fisiológicas o conductuales de una persona física, como imágenes faciales o datos dactiloscópicos;"),
    ("identificación biométrica", "biometric identification", "el reconocimiento automatizado de características humanas de tipo físico, fisiológico, conductual o psicológico para determinar la identidad de una persona física comparando sus datos biométricos con los datos biométricos de personas almacenados en una base de datos;"),
    ("verificación biométrica", "biometric verification", "la verificación automatizada y uno-a-uno, incluida la autenticación, de la identidad de las personas físicas mediante la comparación de sus datos biométricos con los datos biométricos facilitados previamente;"),
    ("categorías especiales de datos personales", "special categories of personal data", "las categorías de datos personales a que se refieren el artículo 9, apartado 1, del Reglamento (UE) 2016/679, el artículo 10 de la Directiva (UE) 2016/680 y el artículo 10, apartado 1, del Reglamento (UE) 2018/1725;"),
    ("datos operativos sensibles", "sensitive operational data", "los datos operativos relacionados con actividades de prevención, detección, investigación o enjuiciamiento de delitos cuya divulgación podría poner en peligro la integridad de las causas penales;"),
    ("sistema de reconocimiento de emociones", "emotion recognition system", "un sistema de IA destinado a distinguir o inferir las emociones o las intenciones de las personas físicas a partir de sus datos biométricos;"),
    ("sistemas de reconocimiento de emociones", "emotion recognition system", "un sistema de IA destinado a distinguir o inferir las emociones o las intenciones de las personas físicas a partir de sus datos biométricos;"),
    ("sistema de categorización biométrica", "biometric categorisation system", "un sistema de IA destinado a incluir a las personas físicas en categorías específicas en función de sus datos biométricos, a menos que sea accesorio a otro servicio comercial y estrictamente necesario por razones técnicas objetivas;"),
    ("sistemas de categorización biométrica", "biometric categorisation system", "un sistema de IA destinado a incluir a las personas físicas en categorías específicas en función de sus datos biométricos, a menos que sea accesorio a otro servicio comercial y estrictamente necesario por razones técnicas objetivas;"),
    ("sistema de identificación biométrica remota en tiempo real", "real-time remote biometric identification system", "un sistema de identificación biométrica remota, en el que la recogida de los datos biométricos, la comparación y la identificación se producen sin una demora significativa; engloba no solo la identificación instantánea, sino también, a fin de evitar la elusión, demoras mínimas limitadas;"),
    ("sistemas de identificación biométrica remota en tiempo real", "real-time remote biometric identification system", "un sistema de identificación biométrica remota, en el que la recogida de los datos biométricos, la comparación y la identificación se producen sin una demora significativa; engloba no solo la identificación instantánea, sino también, a fin de evitar la elusión, demoras mínimas limitadas;"),
    ("sistema de identificación biométrica remota en diferido", "post-remote biometric identification system", "cualquier sistema de identificación biométrica remota que no sea un sistema de identificación biométrica remota en tiempo real;"),
    ("sistemas de identificación biométrica remota en diferido", "post-remote biometric identification system", "cualquier sistema de identificación biométrica remota que no sea un sistema de identificación biométrica remota en tiempo real;"),
    ("sistema de identificación biométrica remota", "remote biometric identification system", "un sistema de IA destinado a identificar a las personas físicas sin su participación activa y generalmente a distancia comparando sus datos biométricos con los que figuran en una base de datos de referencia;"),
    ("sistemas de identificación biométrica remota", "remote biometric identification system", "un sistema de IA destinado a identificar a las personas físicas sin su participación activa y generalmente a distancia comparando sus datos biométricos con los que figuran en una base de datos de referencia;"),
    ("espacio de acceso público", "publicly accessible space", "cualquier lugar físico, de propiedad privada o pública, al que pueda acceder un número indeterminado de personas físicas, con independencia de que deban cumplirse determinadas condiciones de acceso y con independencia de las posibles restricciones de capacidad;"),
    ("espacios de acceso público", "publicly accessible space", "cualquier lugar físico, de propiedad privada o pública, al que pueda acceder un número indeterminado de personas físicas, con independencia de que deban cumplirse determinadas condiciones de acceso y con independencia de las posibles restricciones de capacidad;"),
    ("autoridad garante del cumplimiento del Derecho", "law enforcement authority", "a)toda autoridad pública competente para la prevención, la investigación, la detección o el enjuiciamiento de delitos o la ejecución de sanciones penales, incluidas la protección frente a amenazas para la seguridad pública y la prevención de dichas amenazas, o<br>b\)cualquier otro organismo o entidad a quien el Derecho del Estado miembro haya confiado el ejercicio de la autoridad pública y las competencias públicas a efectos de prevención, investigación, detección o enjuiciamiento de delitos o ejecución de sanciones penales, incluidas la protección frente a amenazas para la seguridad pública y la prevención de dichas amenazas;"),
    ("autoridades garantes del cumplimiento del Derecho", "law enforcement authority", "a)toda autoridad pública competente para la prevención, la investigación, la detección o el enjuiciamiento de delitos o la ejecución de sanciones penales, incluidas la protección frente a amenazas para la seguridad pública y la prevención de dichas amenazas, o<br>b\)cualquier otro organismo o entidad a quien el Derecho del Estado miembro haya confiado el ejercicio de la autoridad pública y las competencias públicas a efectos de prevención, investigación, detección o enjuiciamiento de delitos o ejecución de sanciones penales, incluidas la protección frente a amenazas para la seguridad pública y la prevención de dichas amenazas;"),
    ("garantía del cumplimiento del Derecho", "law enforcement", "las actividades realizadas por las autoridades garantes del cumplimiento del Derecho, o en su nombre, para la prevención, la investigación, la detección o el enjuiciamiento de delitos o la ejecución de sanciones penales, incluidas la protección frente a amenazas para la seguridad pública y la prevención de dichas amenazas;"),
    ("garantías del cumplimiento del Derecho", "law enforcement", "las actividades realizadas por las autoridades garantes del cumplimiento del Derecho, o en su nombre, para la prevención, la investigación, la detección o el enjuiciamiento de delitos o la ejecución de sanciones penales, incluidas la protección frente a amenazas para la seguridad pública y la prevención de dichas amenazas;"),
    ("Oficina de IA", "AI Office", "la función de la Comisión consistente en contribuir a la implantación, el seguimiento y la supervisión de los sistemas de IA y modelos de IA de uso general, y a la gobernanza de la IA prevista por la Decisión de la Comisión de 24 de enero de 2024; las referencias hechas en el presente Reglamento a la Oficina de IA se entenderán hechas a la Comisión;"),
    ("autoridad nacional competente", "national competent authority", "una autoridad notificante o una autoridad de vigilancia del mercado; en lo que respecta a sistemas de IA puestos en servicio o utilizados por instituciones, órganos y organismos de la Unión, las referencias hechas en el presente Reglamento a autoridades nacionales competentes o a autoridades de vigilancia del mercado se interpretarán como referencias al Supervisor Europeo de Protección de Datos;"),
    ("autoridades nacionales competentes", "national competent authority", "una autoridad notificante o una autoridad de vigilancia del mercado; en lo que respecta a sistemas de IA puestos en servicio o utilizados por instituciones, órganos y organismos de la Unión, las referencias hechas en el presente Reglamento a autoridades nacionales competentes o a autoridades de vigilancia del mercado se interpretarán como referencias al Supervisor Europeo de Protección de Datos;"),
    ("incidente grave", "serious incident", "un incidente o defecto de funcionamiento de un sistema de IA que, directa o indirectamente, tenga alguna de las siguientes consecuencias:<br>a) el fallecimiento de una persona o un perjuicio grave para su salud;<br>b) una alteración grave e irreversible de la gestión o el funcionamiento de infraestructuras críticas;<br>c) el incumplimiento de obligaciones en virtud del Derecho de la Unión destinadas a proteger los derechos fundamentales;<br>d) daños graves a la propiedad o al medio ambiente;"),
    ("incidentes graves", "serious incident", "un incidente o defecto de funcionamiento de un sistema de IA que, directa o indirectamente, tenga alguna de las siguientes consecuencias:<br>a) el fallecimiento de una persona o un perjuicio grave para su salud;<br>b) una alteración grave e irreversible de la gestión o el funcionamiento de infraestructuras críticas;<br>c) el incumplimiento de obligaciones en virtud del Derecho de la Unión destinadas a proteger los derechos fundamentales;<br>d) daños graves a la propiedad o al medio ambiente;"),
    ("datos personales", "personal data", "los datos personales tal como se definen en el artículo 4, punto 1, del Reglamento (UE) 2016/679;"),
    ("dato personal", "personal data", "los datos personales tal como se definen en el artículo 4, punto 1, del Reglamento (UE) 2016/679;"),
    ("datos no personales", "non-personal data", "los datos que no sean datos personales tal como se definen en el artículo 4, punto 1, del Reglamento (UE) 2016/679;"),
    ("elaboración de perfiles", "profiling", "la elaboración de perfiles tal como se define en el artículo 4, punto 4, del Reglamento (UE) 2016/679;"),
    ("plan de la prueba en condiciones reales", "real-world testing plan", "un documento que describe los objetivos, la metodología, el ámbito geográfico, poblacional y temporal, el seguimiento, la organización y la realización de la prueba en condiciones reales;"),
    ("plan del espacio controlado de pruebas", "sandbox plan", "un documento acordado entre el proveedor participante y la autoridad competente en el que se describen los objetivos, las condiciones, el calendario, la metodología y los requisitos para las actividades realizadas en el espacio controlado de pruebas;"),
    ("espacio controlado de pruebas para la IA", "AI regulatory sandbox", "un marco controlado establecido por una autoridad competente que ofrece a los proveedores y proveedores potenciales de sistemas de IA la posibilidad de desarrollar, entrenar, validar y probar, en condiciones reales cuando proceda, un sistema de IA innovador, con arreglo a un plan del espacio controlado de pruebas y durante un tiempo limitado, bajo supervisión regulatoria;"),
    ("alfabetización en materia de IA", "AI literacy", "as capacidades, los conocimientos y la comprensión que permiten a los proveedores, responsables del despliegue y demás personas afectadas, teniendo en cuenta sus respectivos derechos y obligaciones en el contexto del presente Reglamento, llevar a cabo un despliegue informado de los sistemas de IA y tomar conciencia de las oportunidades y los riesgos que plantea la IA, así como de los perjuicios que puede causar;"),
    ("prueba en condiciones reales", "testing in real-world conditions", "la prueba temporal de un sistema de IA para su finalidad prevista en condiciones reales, fuera de un laboratorio u otro entorno de simulación, con el fin de recabar datos sólidos y fiables y evaluar y comprobar la conformidad del sistema de IA con los requisitos del presente Reglamento; si se cumplen todas las condiciones establecidas en el artículo 57 o 60, no se considerará una introducción en el mercado o una puesta en servicio del sistema de IA en el sentido de lo dispuesto en el presente Reglamento;"),
    ("sujeto","subject", "a los efectos de la prueba en condiciones reales, una persona física que participa en la prueba en condiciones reales;"),
    ("consentimiento informado", "informed consent", "la expresión libre, específica, inequívoca y voluntaria por parte de un sujeto de su voluntad de participar en una determinada prueba en condiciones reales tras haber sido informado de todos los aspectos de la prueba que sean pertinentes para su decisión de participar;"),
    ("ultrasuplantación", "deep fake", "un contenido de imagen, audio o vídeo generado o manipulado por una IA que se asemeja a personas, objetos, lugares, entidades o sucesos reales y que puede inducir a una persona a pensar erróneamente que son auténticos o verídicos;"),
    ("infracción generalizada", "widespread infringement", "todo acto u omisión contrario al Derecho de la Unión por el que se protegen los intereses de las personas y que:<br>a)haya perjudicado o pueda perjudicar los intereses colectivos de personas que residen en al menos dos Estados miembros distintos de aquel en el que:<br>i)se originó o tuvo lugar el acto u omisión,<br>ii)esté ubicado o establecido el proveedor de que se trate o, en su caso, su representante autorizado, o<br>iii)esté establecido el responsable del despliegue en el momento de cometer la infracción;<br>b)haya perjudicado, perjudique o pueda perjudicar los intereses colectivos de las personas y tenga características comunes —incluidas la misma práctica ilícita o la vulneración del mismo interés— y sea cometido simultáneamente por el mismo operador en al menos tres Estados miembros;"),
    ("infraestructura crítica", "critical infrastructure", "una infraestructura crítica tal como se define en el artículo 2, punto 4, de la Directiva (UE) 2022/2557;"),
    ("modelo de IA de uso general", "general-purpose AI model", "un modelo de IA, también uno entrenado con un gran volumen de datos utilizando autosupervisión a gran escala, que presenta un grado considerable de generalidad y es capaz de realizar de manera competente una gran variedad de tareas distintas, independientemente de la manera en que el modelo se introduzca en el mercado, y que puede integrarse en diversos sistemas o aplicaciones posteriores, excepto los modelos de IA que se utilizan para actividades de investigación, desarrollo o creación de prototipos antes de su introducción en el mercado;"),
    ("capacidades de gran impacto", "high-impact capabilities", "capacidades que igualan o superan las capacidades mostradas por los modelos de IA de uso general más avanzados;"),
    ("riesgo sistémico", "systemic risk", "un riesgo específico de las capacidades de gran impacto de los modelos de IA de uso general, que tienen unas repercusiones considerables en el mercado de la Unión debido a su alcance o a los efectos negativos reales o razonablemente previsibles en la salud pública, la seguridad, la seguridad pública, los derechos fundamentales o la sociedad en su conjunto, que puede propagarse a gran escala a lo largo de toda la cadena de valor;"),
    ("riesgos sistémicos", "systemic risk", "un riesgo específico de las capacidades de gran impacto de los modelos de IA de uso general, que tienen unas repercusiones considerables en el mercado de la Unión debido a su alcance o a los efectos negativos reales o razonablemente previsibles en la salud pública, la seguridad, la seguridad pública, los derechos fundamentales o la sociedad en su conjunto, que puede propagarse a gran escala a lo largo de toda la cadena de valor;"),
    ("riesgo", "risk", "la combinación de la probabilidad de que se produzca un perjuicio y la gravedad de dicho perjuicio;"),
    ("sistema de IA de uso general", "general-purpose AI system", "un sistema de IA basado en un modelo de IA de uso general y que puede servir para diversos fines, tanto para su uso directo como para su integración en otros sistemas de IA;"),
    ("sistema de IA", "AI system", "un sistema basado en una máquina que está diseñado para funcionar con distintos niveles de autonomía y que puede mostrar capacidad de adaptación tras el despliegue, y que, para objetivos explícitos o implícitos, infiere de la información de entrada que recibe la manera de generar resultados de salida, como predicciones, contenidos, recomendaciones o decisiones, que pueden influir en entornos físicos o virtuales;"),
    ("sistemas de IA", "AI system", "un sistema basado en una máquina que está diseñado para funcionar con distintos niveles de autonomía y que puede mostrar capacidad de adaptación tras el despliegue, y que, para objetivos explícitos o implícitos, infiere de la información de entrada que recibe la manera de generar resultados de salida, como predicciones, contenidos, recomendaciones o decisiones, que pueden influir en entornos físicos o virtuales;"),
    ("operación de coma flotante", "floating-point operation", "cualquier operación o tarea matemática que implique números de coma flotante, que son un subconjunto de los números reales normalmente representados en los ordenadores mediante un número entero de precisión fija elevado por el exponente entero de una base fija;"),

]

def tooltip(soup, texto, tooltip):
    for element in soup.find_all(string=re.compile(r"\b" + texto + "[ ,.;()]+")):
        #print(element.prettify())
        new_element = re.sub(texto, "<a class= 'link-dark' href='#art_3' data-bs-toggle='tooltip' data-bs-placement='top' data-bs-html='true' title='' data-bs-original-title='" + tooltip +"'>"+ texto + "</a>", element)
        element.replace_with(BeautifulSoup(new_element, "html.parser")) 
    return(soup)

def articles_link(soup, articles):
    for a in range(articles, 0, -1):
        texto = "artículo " + str(a)
        for element in soup.find_all(string=re.compile(texto + "[ ,.;()]+[^d]")):
            #print(str(element))
            #new_element = str(element).replace(texto, "<a href='.#art_" + str(a) +"'>" + texto + "</a>")
            new_element = re.sub(texto, "<a href='.#art_" + str(a) +"'>" + texto + "</a>", element)
            element.replace_with(BeautifulSoup(new_element, "html.parser")) 
    return(soup)

def link(soup, texto, href):
    for element in soup.find_all(string=re.compile(r"\b" + texto + "[ ,.;()]+")):
        #print(str(element))
        #new_element = str(element).replace(texto, "<a href='.#art_" + str(a) +"'>" + texto + "</a>")
        new_element = re.sub(texto, "<a href='" + href +"'>" + texto + "</a>", element)
        element.replace_with(BeautifulSoup(new_element, "html.parser")) 
    return(soup)


with open('./template/template.html', encoding='utf-8') as f:
    soup = BeautifulSoup(f.read(), features="html.parser")
    
    soup = link(soup, "artículo 2 del Tratado de la Unión Europea", "https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=celex%3A12016ME%2FTXT")
    soup = link(soup, "artículo 2 del TUE", "https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=celex%3A12016ME%2FTXT")
    soup = link(soup, "artículo 6 del TUE", "https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=celex%3A12016ME%2FTXT")
    soup = link(soup, "artículo 114 del Tratado de Funcionamiento de la Unión Europea", "https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=celex%3A12016ME%2FTXT")
    soup = link(soup, "artículo 114 del TFUE", "https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=celex%3A12016ME%2FTXT")
    soup = link(soup, "artículo 16 del TFUE", "https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=celex%3A12016ME%2FTXT")
    soup = link(soup, "Tratado de Funcionamiento de la Unión Europea", "https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=celex%3A12016ME%2FTXT")
    soup = link(soup, "TFUE", "https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=celex%3A12016ME%2FTXT")
    soup = link(soup, "Tratado de la Unión Europea", "https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=celex%3A12016ME%2FTXT")
    soup = link(soup, "TUE", "https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=celex%3A12016ME%2FTXT")
    
    for t in terminos:
        soup = tooltip(soup, t[0],"en: " + t[1] + "<br>" + t[2])
    
    soup = articles_link(soup, 113)  
    
    
    #soup = tooltip(soup, "organismo notificado","en: notified body<br>un organismo de evaluación de la conformidad notificado con arreglo al presente Reglamento y a otros actos pertinentes de la legislación de armonización de la Unión;")
    #soup = tooltip(soup, "organismos notificados","un organismo de evaluación de la conformidad notificado con arreglo al presente Reglamento y a otros actos pertinentes de la legislación de armonización de la Unión;")
    #soup = tooltip(soup, "representante autorizado","una persona física o jurídica ubicada o establecida en la Unión que haya recibido y aceptado el mandato por escrito de un proveedor de un sistema de IA o de un modelo de IA de uso general para cumplir las obligaciones y llevar a cabo los procedimientos establecidos en el presente Reglamento en representación de dicho proveedor;")
    #soup = tooltip(soup, "distribuidor", "una persona física o jurídica que forme parte de la cadena de suministro, distinta del proveedor o el importador, que comercialice un sistema de IA en el mercado de la Unión;")
   
    with open('./index.html', 'w', encoding='utf-8') as f:
        f.write(str(soup))